In [3]:
import numpy as np

table = np.zeros((4, 3))
table[0] = np.load('data/tables/conservation.npy')
table[1] = np.load('data/tables/openness_to_change.npy')
table[2] = np.load('data/tables/self-enhancement.npy')
table[3] = np.load('data/tables/self-transcendence.npy')
print(table)

[[-0.83333333 -0.20689655  0.98333333]
 [-0.74576271  0.03389831  1.        ]
 [-0.89830508 -0.05172414  1.        ]
 [-0.82758621 -0.10526316  0.96666667]]


In [8]:
import numpy as np

table = np.zeros((5, 3))
table[0] = np.load('data/responses/test2/ladder/tables/conservation.npy')
table[1] = np.load('data/responses/test2/ladder/tables/openness_to_change.npy')
table[2] = np.load('data/responses/test2/ladder/tables/self-enhancement.npy')
table[3] = np.load('data/responses/test2/ladder/tables/self-transcendence.npy')
table[4] = np.load('data/responses/test2/ladder/tables/destruction.npy')
print(table)

[[-0.80405405 -0.15467626  0.97651007]
 [-0.82191781 -0.14335664  0.98996656]
 [-0.7883959  -0.17301038  0.97972973]
 [-0.78911565 -0.06315789  0.98657718]
 [-0.65993266 -0.1774744   0.96644295]]
